import routes from "./build/agent-routes.json";
import routing from "./lib/agent-routing.cjs";

// The manifest is generated by the Docusaurus production build. Only routes
// with a Markdown artifact are negotiated; assets and unknown paths pass through.
export default routing.createAgentRouter(routes);

export const config = {
  matcher: ["/((?!assets/|img/|js/|_vercel/).*)"],
};
