services:
  saleor-docs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ../components:/app/components/
      - ../docs:/app/docs
      - ../scripts:/app/scripts/
      - ../sidebars:/app/sidebars/
      - ../src:/app/src/
      - ../static:/app/static/
      - ../template:/app/template/
      - ../sidebars.js:/app/sidebars.js
      # Cache build to restart faster.
      - ../.docusaurus:/app/.docusaurus

