version: "3.8"

services:
  docusaurus2-graphql-doc-generator:
    image: docusaurus2-graphql-doc-generator
    build:
      context: .
      dockerfile: ./tests/e2e/docker/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - "./tests/e2e/specs:/usr/src/app/docusaurus2/__tests__/specs"
      - "./tests/e2e/jest.config.js:/usr/src/app/docusaurus2/__tests__/jest.config.js"
      - "./tests/e2e/docusaurus2-graphql-doc-generator.config.json:/usr/src/app/docusaurus2/docusaurus2-graphql-doc-generator.config.json"
      - "./tests/e2e/scripts/start-demo.sh:/usr/src/app/docusaurus2/start-demo.sh"
      - "./tests/__data__:/usr/src/app/docusaurus2/data"
    container_name: docusaurus2-graphql-doc-generator
