export const selfHosting = [
  "setup/overview",
  "setup/docker-compose",
  "setup/docker-images",
  "setup/configuration",
  "setup/read-replicas",
  "setup/windows",
  {
    type: "category",
    label: "Development",
    items: [
      "developer/running-saleor/debugging-emails",
      "developer/running-saleor/exposing-instance",
    ],
  },
  {
    type: "category",
    label: "Deploying",
    items: ["setup/deploy-do", "setup/deploy-kubernetes", "setup/deploy-linux"],
  },
  {
    type: "category",
    label: "Monitoring",
    items: ["setup/monitoring-jaeger", "setup/monitoring-sentry"],
  },
  {
    type: "category",
    label: "Storing Files",
    items: ["setup/media-gcs", "setup/media-s3"],
  },
  {
    type: "category",
    label: "Upgrade Guides",
    items: [
      "setup/upgrading",
      {
        type: "autogenerated",
        dirName: "upgrade-guides",
      },
    ],
  },
];
