const { title, chapterTitle, hr } = require("./utils");

export const upgradeGuidesSidebar = [
  chapterTitle("upgrade-guides/index", "Upgrade Guides", "guides"),
  hr(),
  title("Saleor Core"),
  {
    type: "autogenerated",
    dirName: "upgrade-guides/core",
  },
];
