const { title, chapterTitle, hr } = require("./utils");

export const upgradeGuidesSidebar = [
  chapterTitle("upgrade-guides/index", "Upgrade guides", "guides"),
  hr(),
  title("Saleor Core"),
  {
    type: "autogenerated",
    dirName: "upgrade-guides/core",
  },
  title("Adyen app"),
  title("AvaTax app"),
];
