name: "Check spelling"
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@934c74da3775ac844ec89503f666f67efb427fed # v6.8.1
        with:
          # Note: before changing this line, update the package.json's "check-spelling" script.
          files: "**/*.{jsx,js,md,mdx}"
