name: QA

on:
  push:
    branches:
      - main
  pull_request:

env:
  HUSKY: 0

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"

      - run: npm ci

      - run: npm run lint
