name: Update CLI docs

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "10 20 * * 1-5" # workdays at 20:10

env:
  HUSKY: 0

jobs:
  check_saleor_release:
    name: Update CLI docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"

      - name: Checkout CLI repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: saleor/cli
          path: cli

      - name: Remove docs/cli
        run: rm -rf docs/cli

      - name: Copy CLI docs
        run: cp -r cli/docs/cli docs/

      - name: Remove CLI repository
        run: rm -rf cli

      - run: npm ci

      - name: Lint changes
        run: npm run lint

      - name: Show changed files
        run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          branch: bot-update-cli-3.x
          commit-message: "Update CLI docs"
          title: "Update CLI docs"
          body: |
            Pull request auto-generated by bot
          labels: |
            :robot: bot
